<a href="https://colab.research.google.com/github/Navyasri28/Python-practices/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

NumPy, short for Numerical Python, is an essential library for numerical computations in Python. It offers robust support for large-scale, multi-dimensional arrays and matrices, and includes a variety of advanced mathematical functions to work with these arrays efficiently.

**Advantages of using NumPy over standard Python lists include:**
- NumPy arrays use less memory and execute operations more quickly.
- NumPy offers an extensive collection of mathematical functions and operations tailored for scientific computing.
- NumPy arrays seamlessly integrate with other scientific computing libraries such as SciPy and Matplotlib.

**Installation:**

To install NumPy, you can use the Python package manager pip. Here are the steps to install NumPy:

1)Open a terminal or command prompt.

2)Run the following command:

In [ ]:
pip install numpy


If you are using a specific Python environment or a virtual environment, make sure it is activated before running the command.

Alternatively, if you are using Anaconda, you can install NumPy using the conda package manager:

1)Open a terminal or Anaconda Prompt.

2)Run the following command:

In [ ]:
conda install numpy

Both methods will download and install the latest version of NumPy and its dependencies.

**NumPy arrays** are the central data structure in NumPy, designed for efficient and optimized numerical operations. They resemble Python lists but offer enhanced performance. Here are some commonly used attributes of NumPy arrays:

1. **`ndarray.ndim`**: Returns the number of dimensions (axes) of the array.
2. **`ndarray.shape`**: Returns a tuple representing the dimensions of the array (e.g., (rows, columns) for a 2D array).
3. **`ndarray.size`**: Returns the total number of elements in the array.
4. **`ndarray.dtype`**: Returns the data type of the array’s elements.
5. **`ndarray.itemsize`**: Returns the size (in bytes) of each element in the array.
6. **`ndarray.nbytes`**: Returns the total number of bytes consumed by the elements of the array.
7. **`ndarray.T`**: Returns the transposed array (i.e., rows become columns and vice versa).

These attributes provide essential information about the array and are useful for understanding and manipulating array data.

1. ndarray.ndim

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Number of dimensions:", arr.ndim)


2)ndarray.shape

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:", arr.shape)


3)ndarray.size

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Total number of elements:", arr.size)


4. ndarray.dtype

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Data type of elements:", arr.dtype)


5. ndarray.itemsize

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Size of each element (in bytes):", arr.itemsize)


6. ndarray.nbytes

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Total bytes consumed by elements:", arr.nbytes)


7. ndarray.T


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Transposed array:\n", arr.T)


**Numpy Array Operations and Broadcasting**

NumPy provides a variety of operations that can be performed on arrays, leveraging the concept of broadcasting to efficiently handle operations on arrays of different shapes. Here are some examples to illustrate these operations and broadcasting:

**Basic Array Operations**

**1)Element-wise Operations**

Addition, subtraction, multiplication, and division can be performed element-wise.

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


**2)Universal Functions (ufuncs)**

NumPy provides a set of universal functions like np.sin, np.cos, np.exp, etc., that operate element-wise on arrays.

In [2]:
import numpy as np

arr = np.array([0, np.pi/2, np.pi])
print("Sine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Exponential:", np.exp(arr))


Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Exponential: [ 1.          4.81047738 23.14069263]


3)Aggregations

Functions like sum, mean, max, and min can be used to aggregate values.

In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())


Sum: 21
Mean: 3.5
Max: 6
Min: 1


**Broadcasting**

Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array along the missing dimensions. Here are some examples:

1)Scalar and Array

Adding a scalar to an array broadcasts the scalar across all elements of the array.

In [4]:
import numpy as np

arr = np.array([1, 2, 3])
print("Add scalar to array:", arr + 1)


Add scalar to array: [2 3 4]


**Array of Different Shapes:**

Arrays of different shapes can be broadcasted to perform operations.

In [5]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

print("Add arrays of different shapes:\n", arr1 + arr2)


Add arrays of different shapes:
 [[2 4 6]
 [5 7 9]]


**Broadcasting Rules**

Arrays are compatible for broadcasting if:
They have the same shape.
One of the arrays has a size of 1 along the dimension.

In [6]:
import numpy as np

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([4, 5, 6])

print("Broadcasting example:\n", arr1 + arr2)


Broadcasting example:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


**Advanced Broadcasting**

**Broadcasting with Higher Dimensions**

Broadcasting works with higher-dimensional arrays as well.

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])

print("Higher dimension broadcasting:\n", arr1 + arr2)


Higher dimension broadcasting:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


 **INDEXING AND SLICING**

Indexing and slicing are fundamental operations in NumPy, allowing you to access and manipulate subsets of array data. Here are some examples to demonstrate these operations:

**Indexing**

**Basic Indexing**

Accessing elements using their index.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Element at index 0:", arr[0])
print("Element at index 3:", arr[3])


Element at index 0: 1
Element at index 3: 4


**2D Array Indexing**

Accessing elements in a 2D array

In [9]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at row 1, column 2:", arr[1, 2])
print("Element at row 0, column 1:", arr[0, 1])


Element at row 1, column 2: 6
Element at row 0, column 1: 2


**Negative Indexing**

Accessing elements using negative indices

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Last element:", arr[-1])
print("Second to last element:", arr[-2])


Last element: 5
Second to last element: 4


**Slicing**

**1D Array Slicing**

Extracting a subset of elements from a 1D array.

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Elements from index 1 to 3:", arr[1:4])
print("Elements from the start to index 2:", arr[:3])
print("Elements from index 3 to the end:", arr[3:])


Elements from index 1 to 3: [2 3 4]
Elements from the start to index 2: [1 2 3]
Elements from index 3 to the end: [4 5]


**2D Array Slicing**

Extracting subsets of elements from a 2D array.



In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("First two rows:\n", arr[:2])
print("Last two columns:\n", arr[:, -2:])
print("Middle subarray:\n", arr[1:3, 1:3])


First two rows:
 [[1 2 3]
 [4 5 6]]
Last two columns:
 [[2 3]
 [5 6]
 [8 9]]
Middle subarray:
 [[5 6]
 [8 9]]


**Step Slicing**

Using step values to slice arrays.


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Every second element:", arr[::2])
print("Elements in reverse order:", arr[::-1])


Every second element: [1 3 5]
Elements in reverse order: [5 4 3 2 1]


**Boolean Indexing**

Using boolean conditions to index arrays.

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Elements greater than 2:", arr[arr > 2])


Elements greater than 2: [3 4 5]


**Fancy Indexing**

Using arrays of indices to access specific elements.

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2, 4])
print("Elements at indices 0, 2, and 4:", arr[indices])


Elements at indices 0, 2, and 4: [1 3 5]


**Combining Indexing and Slicing**

**2D Array Exampl**e

Combining indexing and slicing to access elements in a 2D array.

In [16]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Elements in the first two rows and first two columns:\n", arr[:2, :2])
print("Last element of each row:", arr[:, -1])


Elements in the first two rows and first two columns:
 [[1 2]
 [4 5]]
Last element of each row: [3 6 9]


**Array manipulatio**n


Array manipulation is a key feature of NumPy, providing various functions to modify, reshape, and transform arrays. Here are some examples of common array manipulation techniques:

**Reshaping Arrays**
**Reshape**

Change the shape of an array without changing its data.

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print("Original array:", arr)
print("Reshaped array:\n", reshaped_arr)


Original array: [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]


**Flatten**

Convert a multi-dimensional array into a 1D array

In [18]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print("Flattened array:", flattened_arr)


Flattened array: [1 2 3 4 5 6]


**Joining Arrays**


**Concatenate**

Join a sequence of arrays along an existing axis.

In [19]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenated array along axis 0:\n", concatenated_arr)


Concatenated array along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


**Stack**

Join a sequence of arrays along a new axis.

In [20]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2), axis=1)
print("Stacked array along new axis:\n", stacked_arr)


Stacked array along new axis:
 [[1 4]
 [2 5]
 [3 6]]


**Horizontal Stack (hstack)**

Stack arrays in sequence horizontally (column-wise).


In [21]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
hstacked_arr = np.hstack((arr1, arr2))
print("Horizontally stacked array:", hstacked_arr)


Horizontally stacked array: [1 2 3 4 5 6]


**Vertical Stack (vstack)**

Stack arrays in sequence vertically (row-wise).

In [22]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
vstacked_arr = np.vstack((arr1, arr2))
print("Vertically stacked array:\n", vstacked_arr)


Vertically stacked array:
 [[1 2 3]
 [4 5 6]]


**Splitting Arrays**

**Split**

Split an array into multiple sub-arrays.

In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)
print("Split array into 3 parts:", split_arr)


Split array into 3 parts: [array([1, 2]), array([3, 4]), array([5, 6])]


**Horizontal Split (hsplit)**

Split an array into multiple sub-arrays horizontally (column-wise).



In [24]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_arr = np.hsplit(arr, 3)
print("Horizontally split array into 3 parts:\n", hsplit_arr)


Horizontally split array into 3 parts:
 [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


**Adding/Removing Elements**


**Append**

Append elements to an array

In [25]:
import numpy as np

arr = np.array([1, 2, 3])
appended_arr = np.append(arr, [4, 5, 6])
print("Array after append:", appended_arr)


Array after append: [1 2 3 4 5 6]


**Insert**

Insert elements into an array at a specified index

In [26]:
import numpy as np

arr = np.array([1, 2, 3])
inserted_arr = np.insert(arr, 1, [4, 5])
print("Array after insert:", inserted_arr)


Array after insert: [1 4 5 2 3]


**Delete**

Delete elements from an array.

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
deleted_arr = np.delete(arr, [1, 3])
print("Array after delete:", deleted_arr)


Array after delete: [1 3 5]
